# Lab 2 - NumPy and Vectorization

## 1. Create a 2D NumPy Array

In this section, we create a 2D NumPy array and calculate the mean of each row and the maximum value of each column.

In [3]:
import numpy as np
array=np.array([
    [1,2,3],[4,5,6],[7,8,9]
])
row_means=array.mean(axis=0)
row_means

array([4., 5., 6.])

In [4]:
col_max=array.max(axis=0)
col_max

array([7, 8, 9])

## 2. Normalize Each Column

In this section, we normalize each column of the NumPy array to a range between 0 and 1.

The normalization formula is:

`(value - column_min) / (column_max - column_min)`

In [8]:
col_min = array.min(axis=0)
col_max = array.max(axis=0)
normalize = (array - col_min) / (col_max - col_min)
normalize

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

## 3. Use Broadcasting

In this section, we calculate the mean of each column and subtract the column means from every row.

NumPy broadcasting allows the column means to be applied to all rows without using an explicit Python loop.

In [9]:
col_means = array.mean(axis=0)
col_means

array([4., 5., 6.])

### Subtract Column Means

We subtract the mean of each column from every value in that column.

NumPy automatically broadcasts the column means across all rows.

In [10]:
use_Brodcasting = array - col_means
use_Brodcasting 

array([[-3., -3., -3.],
       [ 0.,  0.,  0.],
       [ 3.,  3.,  3.]])

## 4. Compare Vectorization with a Python Loop

In this section, we compare a vectorized NumPy operation with an equivalent Python loop.

We will measure the execution time of both approaches and compare their performance.

In [13]:
import time
start=time.perf_counter()
vector_result=array*2
vector_time=time.perf_counter()-start
vector_result

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### Python Loop

The same operation is performed using explicit Python loops so that we can compare its execution time with the vectorized NumPy approach.

In [14]:
start=time.perf_counter()
loop_result=np.empty_like(array)

for i in range(array.shape[0]):
    for j in range(array.shape[1]):
        loop_result[i, j]=array[i, j]*2
loop_time=time.perf_counter()-start
loop_result

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
np.array_equal(vector_result, loop_result)

True